{{- if not .Values.externalValkey.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.valkey.secretName" }}
data:
  password: {{ .Values.externalValkey.password }}
{{- end }}
