{{- if not .Values.externalDatabase.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.postgresql.secretName" }}
data:
  hostname: {{ .Values.externalDatabase.hostname | b64enc }}
  database: {{ .Values.externalDatabase.database | b64enc}}
  username: {{ .Values.externalDatabase.username | b64enc }}
  password: {{ .Values.externalDatabase.password | b64enc }}
{{- end }}
